deployment:
  tasks:
    - export DEPLOY_PATH=/home2/himalba4/public_html  # Set the deployment directory
    - /bin/rm -rf $DEPLOY_PATH/*                     # Remove old files before deployment
    - /bin/cp -R * $DEPLOY_PATH                      # Copy new files to the deployment directory
    - /bin/find $DEPLOY_PATH -type d -exec chmod 755 {} \; # Set correct permissions for directories
    - /bin/find $DEPLOY_PATH -type f -exec chmod 644 {} \; # Set correct permissions for files
